-- 코드를 입력하세요
SELECT A.HISTORY_ID, A.CAR_ID, TO_CHAR(A.START_DATE,'YYYY-MM-DD'),TO_CHAR(A.END_DATE,'YYYY-MM-DD'),
CASE WHEN (END_DATE-START_DATE +1)>=30 THEN '장기 대여'
                 ELSE '단기 대여'
                 END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE TO_CHAR(START_DATE,'YYYY-MM-DD') BETWEEN '2022-09-01' AND '2022-09-30'
ORDER BY HISTORY_ID DESC;